name: "Connect4"

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'connect4|')
    steps:

    - name: Set env vars
      run: |
        echo ::set-env name=REPOSITORY::${{ github.repository }}
        echo ::set-env name=EVENT_ISSUE_NUMBER::${{ github.event.issue.number }}
        echo ::set-env name=EVENT_USER_LOGIN::${{ github.event.issue.user.login }}

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1

    - name: Setup Gems
      run: |
        gem install octokit -N --silent
    
    - name: Test
      run: |
        sudo apt-get install tree
        tree .. -L 4

    - name: Play
      run: |
        ruby <<- EORUBY
          require '../connect4/runner'
          
          runner = Connect4::Runner.new(
            github_token: "${{ secrets.GITHUB_TOKEN }}",
            issue: ENV.fetch('EVENT_ISSUE_NUMBER'),
            repository: ENV.fetch('REPOSITORY'),
          )
          runner.parse_input('${{ github.event.issue.title }}')
        EORUBY
